In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [ ]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activation(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0, 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[ self.X, -np.ones((len(self.X), 1))]
    print(f"X with bias {X_with_bias}")

    for epoch in range(self.epochs):
      print(f"Epoch {epoch}")
      y_hat = self.activation(X_with_bias, self.weights)
      print(f"Predicted value {y_hat}")
      error = self.y - y_hat
      print(f"Error \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"Updated weight \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(X), 1))]
    return self.activation(X_with_bias, self.weights)

In [ ]:
data = {
  "x1": [0,0,1,1],
  "x2": [0,1,0,1],
  "y": [0,0,0,1]
}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
X = AND.drop("y", axis=1)
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [ ]:
b = np.c_[X, -np.ones((len(X), 1))]
b

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [ ]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(X, y)

self.weights: [-2.33631685e-07 -3.85750329e-05 -1.12372225e-04]
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch 0
Predicted value [1 1 1 1]
Error
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weight
[-0.50000023 -0.50003858  1.49988763]
#############

Epoch 1
Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight
[-2.33631685e-07 -3.85750329e-05  9.99887628e-01]
#############

Epoch 2
Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.49988763]
#############

Epoch 3
Predicted value [0 1 1 1]
Error
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weight
[-2.33631685e-07 -3.85750329e-05  1.49988763e+00]
#############

Epoch 4
Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

Epoch 5
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

Epoch 6
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

Epoch 7
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

Epoch 8
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

Epoch 9
Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.49999977 0.49996142 0.99988763]
#############

In [ ]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,1]}

OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [ ]:
X = OR.drop("y", axis=1)
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [ ]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [-6.23265862e-05  6.99117880e-05 -7.41481147e-06]
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch 0
Predicted value [1 1 0 1]
Error
0   -1
1    0
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99937673e-01  6.99117880e-05 -7.41481147e-06]
#############

Epoch 1
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[4.99937673e-01 6.99117880e-05 4.99992585e-01]
#############

Epoch 2
Predicted value [0 0 0 1]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 0.99993767  0.50006991 -0.50000741]
#############

Epoch 3
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[ 9.99937673e-01  5.00069912e-01 -7.41481147e-06]
#############

Epoch 4
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

Epoch 5
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

Epoch 6
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

Epoch 7
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

Epoch 8
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

Epoch 9
Predicted value [0 1 1 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight
[0.99993767 0.50006991 0.49999259]
#############

In [ ]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [ ]:
X = XOR.drop("y", axis=1)
y = XOR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  0

In [ ]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [-6.94966841e-05  4.79541930e-05 -2.50452223e-05]
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch 0
Predicted value [1 1 0 1]
Error
0   -1
1    0
2    1
3   -1
Name: y, dtype: int64
Updated weight
[-6.94966841e-05 -4.99952046e-01  4.99974955e-01]
#############

Epoch 1
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99930503e-01  4.79541930e-05 -5.00025045e-01]
#############

Epoch 2
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
[-6.94966841e-05 -4.99952046e-01  4.99974955e-01]
#############

Epoch 3
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99930503e-01  4.79541930e-05 -5.00025045e-01]
#############

Epoch 4
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
[-6.94966841e-05 -4.99952046e-01  4.99974955e-01]
#############

Epoch 5
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99930503e-01  4.79541930e-05 -5.00025045e-01]
#############

Epoch 6
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
[-6.94966841e-05 -4.99952046e-01  4.99974955e-01]
#############

Epoch 7
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99930503e-01  4.79541930e-05 -5.00025045e-01]
#############

Epoch 8
Predicted value [1 1 1 1]
Error
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weight
[-6.94966841e-05 -4.99952046e-01  4.99974955e-01]
#############

Epoch 9
Predicted value [0 0 0 0]
Error
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weight
[ 4.99930503e-01  4.79541930e-05 -5.00025045e-01]
#############